name: Generar Reporte LTV

on:
  push:
    branches: [ main ] # Se ejecuta cada vez que subas cambios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Script de LTV
      run: python scripts/procesar_ltv.py

    - name: Guardar Reporte generado
      uses: actions/upload-artifact@v3
      with:
        name: reporte-ltv-final
        path: reportes/resultado_ltv.csv